################################################################################
# Own makefile targets
################################################################################

MAIN_OBJS :=  ./runtime/test_mac.o ./runtime/client_network.o ./runtime/client.o ./runtime/basestation.o
COMMON_OBJS := $(filter-out $(MAIN_OBJS), $(OBJS))
SYSROOT :=--sysroot=/home/lukas/pluto-0.31.sysroot/

# mac layer test
test_mac: $(OBJS) $(USER_OBJS)
	@echo 'Building target: $@'
	@echo 'Invoking: GCC C Linker'
	gcc -o "test_mac" ./runtime/test_mac.o $(COMMON_OBJS) $(USER_OBJS) $(LIBS)
	@echo 'Finished building target: $@'
	@echo ' '
	
# client build
client: $(OBJS) $(USER_OBJS)
	@echo 'Building target: $@'
	@echo 'Invoking: GCC C Linker'
	arm-linux-gnueabihf-gcc -o "client" $(SYSROOT) ./runtime/client.o $(COMMON_OBJS) $(USER_OBJS) $(LIBS)
	@echo 'Finished building target: $@'
	@echo ' '

client-x86: $(OBJS) $(USER_OBJS)
	@echo 'Building target: $@'
	@echo 'Invoking: GCC C Linker'
	gcc -o "client_x86" ./runtime/client.o $(COMMON_OBJS) $(USER_OBJS) $(LIBS)
	@echo 'Finished building target: $@'
	@echo ' '
	
# basestation build
basestation: $(OBJS) $(USER_OBJS)
	@echo 'Building target: $@'
	@echo 'Invoking: GCC C Linker'
	arm-linux-gnueabihf-gcc -o "basestation" $(SYSROOT) ./runtime/basestation.o $(COMMON_OBJS) $(USER_OBJS) $(LIBS)
	@echo 'Finished building target: $@'
	@echo ' '
	
basestation-x86: $(OBJS) $(USER_OBJS)
	@echo 'Building target: $@'
	@echo 'Invoking: GCC C Linker'
	gcc -o "basestation_x86" ./runtime/basestation.o $(COMMON_OBJS) $(USER_OBJS) $(LIBS)
	@echo 'Finished building target: $@'
	@echo ' '