#!/bin/sh
# Server-side demuxing by default

source /etc/device_config

case "$1" in
	start)
		echo -n "Starting dhcpd Daemon & httpd Server: "
		if [ -f "$UDHCPD_CONF" ]; then
		start-stop-daemon -S -q -p /var/run/udhcpd.pid -x /usr/sbin/udhcpd -- $UDHCPD_CONF
		fi
		if [ -f "$UDHCPD_CONF_ETH0" ]; then
			start-stop-daemon -S -q -p /var/run/udhcpd_eth0.pid -x /usr/sbin/udhcpd -- $UDHCPD_CONF_ETH0
		fi
		if [ -f "$UDHCPD_CONF_TAP0" ]; then
			start-stop-daemon -S -q -p /var/run/udhcpd_tap0.pid -x /usr/sbin/udhcpd -- $UDHCPD_CONF_TAP0
		fi

		httpd -h /www
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;

	stop)
		echo -n "Stopping dhcpd Daemon & httpd Server: "
		killall -7 httpd
		start-stop-daemon -K -q -p /var/run/udhcpd.pid 2>/dev/null
		start-stop-daemon -K -q -p /var/run/udhcpd_eth0.pid 2>/dev/null
		start-stop-daemon -K -q -p /var/run/udhcpd_tap0.pid 2>/dev/null
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac