#!/bin/sh

IFACES=$(cat /etc/network/interfaces | grep dhcp | awk -v col=2 '{print $col}')

case "${1}" in
   start)
      for IFACE in $IFACES
      do
         echo "Starting udhcpc for interface $IFACE" | logger
         screen -dmS udhcpc_$IFACE sh -c "udhcpc -i $IFACE -R -t 0 2>&1"
      done      
      ;;

   *)
      echo "Usage: ${0} {start}"
      exit 1
      ;;
esac

exit 0
