#!/bin/sh

case "${1}" in
   start)
      if [ -f "/etc/sysctl.conf" ]; then
         sysctl -q -p
      fi
      ;;

   status)
      sysctl -a
      ;;

   *)
      echo "Usage: ${0} {start|status}"
      exit 1
      ;;
esac

exit 0
