name: Build

on: [push]

jobs:
  tests_and_simulation:
    name: Tests and Simulation

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Install dependencies
      run: |
        sudo apt install libfftw3-dev libconfig-dev automake autoconf
    - name: Build libfec
      run: |
        cd libfec
        ./configure
        sudo make install
    - name: Build liquid-dsp
      run: |
        cd liquid-dsp
        ./bootstrap.sh
        ./configure
        sudo make install
        sudo ldconfig
    - name: Run Unit Tests
      run: |
        mkdir cmake-build-unittests
        cd cmake-build-unittests
        cmake ..
        make unit_tests
        ./unit_tests
    - name: Build Simulation Targets
      run: |
        mkdir cmake-build-simulation
        cd cmake-build-simulation
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        make test_mac
        make test_cfo_estimation

  standalone_binaries:
    name: Standalone Binaries

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Cache custom sysroot
      uses: actions/cache@v2
      env:
        cache-name: custom-sysroot
      with:
        path: build_scripts/build/pluto-custom.sysroot
        key: ${{ env.cache-name }}-${{ hashFiles('build_scripts/create_sysroot.sh') }}
    - name: Install GCC Linaro
      run: |
        wget -q http://releases.linaro.org/components/toolchain/binaries/7.2-2017.11/arm-linux-gnueabihf/gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabihf.tar.xz
        tar xf gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabihf.tar.xz
    - name: Run Buildscript
      run: |
        export PATH=$PATH:$(pwd)/gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabihf/bin
        cd build_scripts
        ./build_standalone_binaries.sh
