name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Install dependencies
      run: |
        sudo apt install libfftw3-dev libconfig-dev automake autoconf
    - name: Build libfec
      run: |
        cd libfec
        ./configure
        sudo make install
    - name: Build liquid-dsp
      run: |
        cd liquid-dsp
        ./bootstrap.sh
        ./configure
        sudo make install
        sudo ldconfig
    - name: Run Unit Tests
      run: |
        mkdir cmake-build-unittests
        cd cmake-build-unittests
        cmake ..
        make unit_tests
        ./unit_tests
    - name: Build Simulation Targets
      run: |
        mkdir cmake-build-simulation
        cd cmake-build-simulation
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        make test_mac
        make test_cfo_estimation
